# Generated by Django 5.0 on 2024-03-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_image_userprofile_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_image',
            new_name='image',
        ),
    ]
